# Generated by Django 4.2.16 on 2025-05-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0021_organization_checksums'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_access', models.CharField(blank=True, choices=[('View', 'View'), ('Edit', 'Edit'), ('None', 'None')], default='View', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('input_file_name', models.TextField()),
                ('decisions', models.JSONField(blank=True, null=True)),
                ('match_types', models.JSONField(blank=True, null=True)),
                ('matched_concepts', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_created_by', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_projects', to='orgs.organization')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_updated_by', related_query_name='%(app_label)s_%(class)ss_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'map_projects',
            },
        ),
        migrations.AddConstraint(
            model_name='mapproject',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None)), fields=('name', 'organization'), name='org_map_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='mapproject',
            constraint=models.UniqueConstraint(condition=models.Q(('organization', None)), fields=('name', 'user'), name='user_map_project_unique'),
        ),
    ]
