# Generated by Django 4.2.16 on 2025-05-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapproject',
            old_name='decisions',
            new_name='matches',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='match_types',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='matched_concepts',
        ),
    ]
