# Generated by Django 4.2.16 on 2025-05-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0002_rename_decisions_mapproject_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapproject',
            name='matches',
        ),
    ]
