# Generated by Django 4.2.16 on 2025-05-14 05:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0003_remove_mapproject_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='matches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
