# Generated by Django 4.2.16 on 2025-06-02 03:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0004_mapproject_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='mapproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
