# Generated by Django 4.2.16 on 2025-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0005_mapproject_columns_mapproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='matching_algorithm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapproject',
            name='target_repo_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
