# Generated by Django 4.2.16 on 2025-06-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0006_mapproject_matching_algorithm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapproject',
            old_name='target_repo_uri',
            new_name='target_repo_url',
        ),
    ]
