# Generated by Django 4.2.16 on 2025-06-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0007_rename_target_repo_uri_mapproject_target_repo_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mapproject',
            name='org_map_project_unique',
        ),
        migrations.RemoveConstraint(
            model_name='mapproject',
            name='user_map_project_unique',
        ),
    ]
