# Generated by Django 4.2.16 on 2025-07-10 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0008_remove_mapproject_org_map_project_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='logs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
