# Generated by Django 4.2.16 on 2025-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0009_mapproject_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='_logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
