# Generated by Django 4.2.16 on 2025-07-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0010_mapproject__logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapproject',
            name='logs',
        ),
    ]
