# Generated by Django 4.2.16 on 2025-07-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0011_remove_mapproject_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapproject',
            old_name='_logs',
            new_name='logs',
        ),
    ]
