# Generated by Django 4.2.16 on 2025-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0012_rename__logs_mapproject_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='include_retired',
            field=models.BooleanField(default=False),
        ),
    ]
