# Generated by Django 4.2.16 on 2025-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0013_mapproject_include_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='match_api_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapproject',
            name='match_api_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
