# Generated by Django 4.2.16 on 2025-08-20 01:56

import core.map_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0014_mapproject_match_api_token_mapproject_match_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='score_configuration',
            field=models.JSONField(blank=True, default=core.map_projects.models.default_score_configuration, null=True),
        ),
    ]
