# Generated by Django 4.2.16 on 2025-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0015_mapproject_score_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='batch_size',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
