# Generated by Django 4.2.16 on 2025-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0016_mapproject_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
