# Generated by Django 4.2.16 on 2025-09-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0017_mapproject_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='candidates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
