# Generated by Django 4.2.16 on 2025-12-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0018_mapproject_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='reranker',
            field=models.BooleanField(default=False),
        ),
    ]
