# Generated by Django 4.2.16 on 2025-12-17 06:01

from django.db import migrations


def scope_logs(apps, schema_editor):
    MapProject = apps.get_model('map_projects', 'MapProject')
    for project in MapProject.objects.all():
        logs = project.logs or {}
        project_logs = [
            {'action': 'Created', 'created_at': str(project.created_at), 'user': project.created_by.username}
        ]
        if project.created_at.strftime('%Y-%m-%d %H:%M:%S') != project.updated_at.strftime('%Y-%m-%d %H:%M:%S'):
            project_logs = [
                {'action': 'Updated', 'created_at': str(project.updated_at), 'user': project.updated_by.username},
                *project_logs
            ]
        project.logs = {'row_logs': logs, 'project_logs': project_logs}
        project.save(update_fields=['logs'])


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0019_mapproject_reranker'),
    ]

    operations = [
        migrations.RunPython(scope_logs)
    ]
