# Generated by Django 4.2.16 on 2026-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0020_auto_20251217_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='bridge_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
