# Generated by Django 4.2.16 on 2026-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0021_mapproject_bridge_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='scispacy_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
