# Generated by Django 4.2.16 on 2026-02-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0022_mapproject_scispacy_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapproject',
            name='reranker',
        ),
    ]
