# Generated by Django 4.2.16 on 2026-02-06 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0023_remove_mapproject_reranker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='algorithms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
