# Generated by Django 4.2.16 on 2026-02-06 06:30

from django.db import migrations

def update_algorithms(apps, schema_editor):
    MapProject = apps.get_model('map_projects', 'MapProject')
    for project in MapProject.objects.filter():
        algos = []
        if project.matching_algorithm == 'es':
            algos.append({
                'id': 'ocl-search',
                'name': 'OCL Search Algorithm',
                'type': 'ocl-search',
                'provider': 'ocl',
                'order': 1,
                'batch_size': 50,
                'concurrent_requests': 2
            })
        if project.matching_algorithm == 'llm':
            algos.append({
                'id': 'ocl-semantic',
                'name': 'OCL Semantic Algorithm',
                'type': 'ocl-semantic',
                'provider': 'ocl',
                'order': 1,
                'batch_size': 10,
                'concurrent_requests': 2,
                'query_params': {
                    'semantic': True
                }
            })
        if project.matching_algorithm == 'custom' and project.match_api_url:
            algos.append({
                'id': 'custom',
                'name': 'Custom Algorithm',
                'type': 'custom',
                'provider': 'external',
                'order': 1,
                'batch_size': project.batch_size,
                'url': project.match_api_url,
                'token': project.match_api_token,
                'concurrent_requests': 1,
            })
        if project.bridge_enabled:
            algos.append({
                'id': 'ocl-ciel-bridge',
                'name': 'OCL CIEL Bridge Terminology',
                'type': 'ocl-ciel-bridge',
                'provider': 'ocl',
                'order': 2,
                'batch_size': 10,
                'concurrent_requests': 2,
                'query_params': {
                    'semantic': True
                },
                'target_repo_url': '/orgs/CIEL/sources/CIEL/'
            })
        if project.scispacy_enabled:
            algos.append({
                'id': 'ocl-scispacy-loinc',
                'name': 'OCL ScispaCy LOINC Algorithm',
                'type': 'ocl-scispacy',
                'provider': 'ocl',
                'order': 3,
                'batch_size': 2,
                'concurrent_requests': 1,
            })
        if algos:
            project.algorithms = algos
            project.save(update_fields=['algorithms'])


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0024_mapproject_algorithms'),
    ]

    operations = [
        migrations.RunPython(update_algorithms),
    ]
