# Generated by Django 4.2.16 on 2026-02-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0025_auto_20260206_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapproject',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='bridge_enabled',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='match_api_token',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='match_api_url',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='matching_algorithm',
        ),
        migrations.RemoveField(
            model_name='mapproject',
            name='scispacy_enabled',
        ),
    ]
