# Generated by Django 4.2.16 on 2026-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0026_remove_mapproject_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='lookup_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
