# Generated by Django 4.2.16 on 2026-02-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0027_mapproject_lookup_config'),
    ]

    operations = [
    ]
