# Generated by Django 4.2.16 on 2026-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0028_auto_20260211_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
