# Generated by Django 4.2.16 on 2026-02-21 02:50

from django.db import migrations
from pydash import get


def populate_analysis_from_row_logs(apps, schema_editor):
    MapProject = apps.get_model('map_projects', 'MapProject')
    for map_project in MapProject.objects.all():
        analysis = {}
        if map_project.logs and not map_project.analysis:
            for row_id, logs in map_project.logs.get('row_logs', {}).items():
                ai_log = next((log for log in sorted(logs, key=lambda log: log.get('created_at', ''), reverse=True) if get(log, 'action') == 'AIRecommendation'), False)
                if ai_log and not get(ai_log, 'extras.error'):
                    response = get(ai_log, 'extras')
                    response['model'] = get(response, 'model.id') or 'anthropic/claude-haiku-4.5'
                    response['timestamp'] = get(ai_log, 'created_at')
                    response['user'] = get(ai_log, 'user')
                    analysis[row_id] = response
            if analysis:
                map_project.analysis = analysis
                map_project.save(update_fields=['analysis'])


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0029_mapproject_analysis'),
    ]

    operations = [
        migrations.RunPython(populate_analysis_from_row_logs),
    ]
