# Generated by Django 5.1.5 on 2026-04-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0030_auto_20260221_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='encoder_model',
            field=models.TextField(blank=True, default='BAAI/bge-reranker-v2-m3', null=True),
        ),
    ]
