# Generated by Django 5.1.15 on 2026-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0031_mapproject_encoder_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapproject',
            name='encoder_model',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
