# Generated by Django 5.1.15 on 2026-05-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0032_alter_mapproject_encoder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='prompt_template_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapproject',
            name='encoder_model',
            field=models.TextField(blank=True, default='BAAI/bge-reranker-v2-m3', null=True),
        ),
    ]
