# Generated by Django 5.1.15 on 2026-05-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0033_mapproject_prompt_template_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapproject',
            old_name='prompt_template_url',
            new_name='prompt_template_key',
        ),
    ]
