# Generated by Django 5.1.15 on 2026-05-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_projects', '0034_rename_prompt_template_url_mapproject_prompt_template_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapproject',
            name='prompt_output_locale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
