# Generated by Django 4.2.16 on 2026-05-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_projects', '0037_mapproject_input_locales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatchRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_access', models.CharField(blank=True, choices=[('View', 'View'), ('Edit', 'Edit'), ('None', 'None')], default='View', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('intended_rows', models.IntegerField()),
                ('completed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('completion_status', models.CharField(default='running', max_length=16)),
                ('trigger_source', models.CharField(max_length=32)),
                ('client_user_agent', models.TextField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_created_by', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('map_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_match_runs', to='map_projects.mapproject')),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='map_projects.automatchrun')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_auto_match_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_updated_by', related_query_name='%(app_label)s_%(class)ss_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automatch_runs',
                'indexes': [models.Index(fields=['map_project', '-started_at'], name='automatch_r_map_pro_967277_idx'), models.Index(fields=['completion_status'], name='automatch_r_complet_d1a277_idx')],
            },
        ),
    ]
