from django.urls import path

from core.collections.feeds import CollectionFeed
from core.concepts.views import ConceptCascadeView
from . import views

urlpatterns = [
    path('', views.CollectionListView.as_view(), name='collection-list'),
    path(
        "<str:collection>/",
        views.CollectionRetrieveUpdateDestroyView.as_view(),
        name='collection-detail'
    ),
    path(
        '<str:collection>/client-configs/',
        views.CollectionClientConfigsView.as_view(),
        name='collection-client-configs'
    ),
    path(
        "<str:collection>/summary/",
        views.CollectionSummaryView.as_view(),
        name='collection-summary'
    ),
    path(
        "<str:collection>/logo/",
        views.CollectionLogoView.as_view(),
        name='collection-logo'
    ),
    path(
        '<str:collection>/versions/',
        views.CollectionVersionListView.as_view(),
        name='collection-version-list'
    ),
    path('<str:collection>/concepts/atom/', CollectionFeed()),
    path(
        '<str:collection>/latest/',
        views.CollectionLatestVersionRetrieveUpdateView.as_view(),
        name='collectionversion-latest-detail'
    ),
    path(
        '<str:collection>/latest/summary/',
        views.CollectionLatestVersionSummaryView.as_view(),
        name='collectionversion-latest-summary'
    ),
    path(
        '<str:collection>/latest/export/',
        views.CollectionVersionExportView.as_view(),
        name='collectionversion-latest-export-detail'
    ),
    path(
        "<str:collection>/concepts/<str:concept>/mappings/",
        views.CollectionVersionConceptMappingsView.as_view(),
        name='concept-mappings'
    ),
    path(
        "<str:collection>/concepts/<str:concept>/<str:concept_version>/mappings/",
        views.CollectionVersionConceptMappingsView.as_view(),
        name='concept-version-mappings'
    ),
    path(
        "<str:collection>/concepts/<str:concept>/$cascade/",
        ConceptCascadeView.as_view(),
        name='concept-cascade'
    ),
    path(
        "<str:collection>/concepts/<str:concept>/<str:concept_version>/",
        views.CollectionVersionConceptRetrieveView.as_view(),
        name='concept-version-detail'
    ),
    path(
        "<str:collection>/concepts/<str:concept>/",
        views.CollectionVersionConceptRetrieveView.as_view(),
        name='concept-detail'
    ),
    path(
        "<str:collection>/concepts/",
        views.CollectionVersionConceptsView.as_view(),
        name='concept-list'
    ),
    path(
        "<str:collection>/mappings/<str:mapping>/<str:mapping_version>/",
        views.CollectionVersionMappingRetrieveView.as_view(),
        name='mapping-version-detail'
    ),
    path(
        "<str:collection>/mappings/<str:mapping>/",
        views.CollectionVersionMappingRetrieveView.as_view(),
        name='mapping-detail'
    ),
    path(
        "<str:collection>/mappings/",
        views.CollectionVersionMappingsView.as_view(),
        name='mapping-list'
    ),
    path(
        '<str:collection>/references/',
        views.CollectionReferencesView.as_view(),
        name='collection-references'
    ),
    path(
        '<str:collection>/references/<str:reference>/',
        views.CollectionReferenceView.as_view(),
        name='collection-reference'
    ),
    path(
        '<str:collection>/references/<str:reference>/concepts/',
        views.CollectionReferenceConceptsView.as_view(),
        name='collection-reference-concepts-list'
    ),
    path(
        '<str:collection>/references/<str:reference>/mappings/',
        views.CollectionReferenceMappingsView.as_view(),
        name='collection-reference-mappings-list'
    ),
    path(
        "<str:collection>/extras/",
        views.CollectionExtrasView.as_view(),
        name='collection-extras'
    ),
    path(
        '<str:collection>/<str:version>/',
        views.CollectionVersionRetrieveUpdateDestroyView.as_view(),
        name='collection-version-detail'
    ),
    path(
        '<str:collection>/<str:version>/summary/',
        views.CollectionVersionSummaryView.as_view(),
        name='collection-version-summary'
    ),
    path(
        '<str:collection>/<str:version>/expansions/',
        views.CollectionVersionExpansionsView.as_view(),
        name='expansion-list'
    ),
    path(
        '<str:collection>/<str:version>/expansions/<str:expansion>/',
        views.CollectionVersionExpansionView.as_view(),
        name='collection-version-expansion-detail'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/<str:concept>/mappings/",
        views.CollectionVersionExpansionConceptMappingsView.as_view(),
        name='concept-mappings'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/<str:concept>/<str:concept_version>/mappings/",  # pylint: disable=line-too-long
        views.CollectionVersionExpansionConceptMappingsView.as_view(),
        name='concept-version-mappings'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/<str:concept>/$cascade/",
        ConceptCascadeView.as_view(),
        name='concept-cascade'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/index/",
        views.ExpansionConceptsIndexView.as_view(),
        name='expansion-concepts-index'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/<str:concept>/<str:concept_version>/",
        views.CollectionVersionExpansionConceptRetrieveView.as_view(),
        name='concept-version-detail'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/concepts/<str:concept>/",
        views.CollectionVersionExpansionConceptRetrieveView.as_view(),
        name='concept-detail'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/mappings/<str:mapping>/<str:mapping_version>/",
        views.CollectionVersionExpansionMappingRetrieveView.as_view(),
        name='mapping-version-detail'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/mappings/index/",
        views.ExpansionMappingsIndexView.as_view(),
        name='expansion-mappings-index'
    ),
    path(
        "<str:collection>/<str:version>/expansions/<str:expansion>/mappings/<str:mapping>/",
        views.CollectionVersionExpansionMappingRetrieveView.as_view(),
        name='mapping-detail'
    ),
    path(
        '<str:collection>/<str:version>/expansions/<str:expansion>/concepts/',
        views.CollectionVersionExpansionConceptsView.as_view(),
        name='collection-version-expansion-concepts'
    ),
    path(
        '<str:collection>/<str:version>/expansions/<str:expansion>/mappings/',
        views.CollectionVersionExpansionMappingsView.as_view(),
        name='collection-version-expansion-mappings'
    ),
    path(
        "<str:collection>/extras/<str:extra>/",
        views.CollectionExtraRetrieveUpdateDestroyView.as_view(),
        name='collection-extra'
    ),
    path(
        '<str:collection>/<str:version>/export/',
        views.CollectionVersionExportView.as_view(), name='collectionversion-export'
    ),
    path(
        "<str:collection>/<str:version>/extras/",
        views.CollectionVersionExtrasView.as_view(),
        name='collectionversion-extras'
    ),
    path(
        "<str:collection>/<str:version>/concepts/<str:concept>/$cascade/",
        ConceptCascadeView.as_view(),
        name='concept-$cascade'
    ),
    path(
        "<str:collection>/<str:version>/concepts/<str:concept>/<str:concept_version>/mappings/",
        views.CollectionVersionConceptMappingsView.as_view(),
        name='concept-version-mappings'
    ),
    path(
        "<str:collection>/<str:version>/concepts/<str:concept>/mappings/",
        views.CollectionVersionConceptMappingsView.as_view(),
        name='concept-mappings'
    ),
    path(
        "<str:collection>/<str:version>/concepts/<str:concept>/<str:concept_version>/",
        views.CollectionVersionConceptRetrieveView.as_view(),
        name='concept-version-detail'
    ),
    path(
        "<str:collection>/<str:version>/concepts/<str:concept>/",
        views.CollectionVersionConceptRetrieveView.as_view(),
        name='concept-detail'
    ),
    path(
        "<str:collection>/<str:version>/concepts/",
        views.CollectionVersionConceptsView.as_view(),
        name='concept-list'
    ),
    path(
        "<str:collection>/<str:version>/mappings/<str:mapping>/<str:mapping_version>/",
        views.CollectionVersionMappingRetrieveView.as_view(),
        name='mapping-version-detail'
    ),
    path(
        "<str:collection>/<str:version>/mappings/<str:mapping>/",
        views.CollectionVersionMappingRetrieveView.as_view(),
        name='mapping-detail'
    ),
    path(
        "<str:collection>/<str:version>/mappings/",
        views.CollectionVersionMappingsView.as_view(),
        name='mapping-list'
    ),
    path(
        '<str:collection>/<str:version>/references/<str:reference>/',
        views.CollectionReferenceView.as_view(),
        name='collectionversion-reference'
    ),
    path(
        '<str:collection>/<str:version>/references/<str:reference>/resolve/',
        views.CollectionReferenceResolveView.as_view(),
        name='collectionversion-reference-resolve'
    ),
    path(
        '<str:collection>/<str:version>/references/<str:reference>/concepts/',
        views.CollectionReferenceConceptsView.as_view(),
        name='collectionversion-reference-concepts-list'
    ),
    path(
        '<str:collection>/<str:version>/references/<str:reference>/mappings/',
        views.CollectionReferenceMappingsView.as_view(),
        name='collectionversion-reference-mappings-list'
    ),
    path(
        '<str:collection>/<str:version>/references/',
        views.CollectionVersionReferencesView.as_view(),
        name='collectionversion-references'
    ),
    path(
        '<str:collection>/<str:version>/processing/',
        views.CollectionVersionProcessingView.as_view(),
        name='collectionversion-processing'
    ),
]
