# Generated by Django 3.0.8 on 2020-07-17 07:30

import core.common.mixins
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('public_access', models.CharField(blank=True, choices=[('View', 'View'), ('Edit', 'Edit'), ('None', 'None')], default='View', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('company', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('mnemonic', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))])),
            ],
            options={
                'db_table': 'organizations',
            },
            bases=(models.Model, core.common.mixins.SourceContainerMixin),
        ),
    ]
