# Generated by Django 3.0.9 on 2020-12-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20200720_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
