# Generated by Django 3.0.7 on 2020-06-22 05:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20200617_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
