# Generated by Django 3.0.9 on 2021-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20210115_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
