# Generated by Django 3.2.7 on 2021-09-14 03:49

from django.db import migrations


def add_org_creator_as_member(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    orgs = Organization.objects.exclude(
        id__in=Organization.members.through.objects.values_list('organization_id', flat=True))
    for org in orgs:
        org.members.set([org.created_by, org.updated_by])


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20210720_1000'),
    ]

    operations = [
        migrations.RunPython(add_org_creator_as_member)
    ]
