# Generated by Django 3.2.8 on 2021-11-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20210914_0349'),
        ('orgs', '0012_remove_organization_internal_reference_id'),
    ]

    operations = [
    ]
