# Generated by Django 3.2.8 on 2021-12-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_merge_20211126_0420'),
        ('orgs', '0013_organization_overview'),
    ]

    operations = [
    ]
