# Generated by Django 3.2.8 on 2021-12-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_merge_20211220_0511'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE organizations ADD COLUMN IF NOT EXISTS overview jsonb;',
            reverse_sql='ALTER TABLE organizations DROP COLUMN overview;'
        ),
    ]
