# Generated by Django 3.2.10 on 2022-04-05 03:56

from django.db import migrations


def add_org_creator_as_member(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for org in Organization.objects.all():
        org.members.add(org.created_by, org.updated_by)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20211220_0731'),
    ]

    operations = [
        migrations.RunPython(add_org_creator_as_member)
    ]
