# Generated by Django 4.0.6 on 2022-09-02 05:17

from django.db import migrations


def add_org_creator_as_member(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for org in Organization.objects.all():
        org.members.add(org.created_by, org.updated_by)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_alter_organization_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(add_org_creator_as_member)
    ]
