# Generated by Django 4.1.7 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_auto_20220902_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
