# Generated by Django 4.2.4 on 2023-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_remove_organization_organizatio_public__2d2963_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
