# Generated by Django 4.1.7 on 2023-03-22 03:49

from django.db import migrations


def remove_mapping_sorting_toggle(apps, schema_editor):
    Toggle = apps.get_model('toggles', 'Toggle')
    Toggle.objects.filter(name='MAPPING_SORTING_TOGGLE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('toggles', '0002_toggle_is_active'),
    ]

    operations = [
        migrations.RunPython(remove_mapping_sorting_toggle)
    ]
