# Generated by Django 3.2.8 on 2021-11-09 09:56
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        BtreeGistExtension()
    ]
