# Generated by Django 3.2.8 on 2021-11-09 09:59
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_create_ext_btree_gist'),
    ]

    operations = [
        TrigramExtension()
    ]
