# Generated by Django 3.2.8 on 2021-11-09 10:03
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_create_ext_trigram'),
    ]

    operations = [
        BtreeGinExtension()
    ]
