# Generated by Django 4.2.4 on 2024-01-11 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0021_organization_checksums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLRegistry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('url', models.URLField()),
                ('name', models.TextField(blank=True, null=True)),
                ('namespace', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_created_by', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_registries', to='orgs.organization')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_updated_by', related_query_name='%(app_label)s_%(class)ss_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'url_registries',
            },
        ),
        migrations.AddConstraint(
            model_name='urlregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('user', 'url'), name='user_url_unique'),
        ),
        migrations.AddConstraint(
            model_name='urlregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('organization__isnull', False)), fields=('organization', 'url'), name='org_url_unique'),
        ),
        migrations.AddConstraint(
            model_name='urlregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('namespace__isnull', True)), fields=('url',), name='global_url_unique'),
        ),
    ]
