# Generated by Django 4.2.4 on 2024-01-22 12:31

import core.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_registry', '0003_alter_urlregistry_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlregistry',
            name='url',
            field=core.common.fields.URIField(),
        ),
    ]
