# Generated by Django 3.0.9 on 2020-12-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0003_organization_logo_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0008_delete_pinneditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='orgs.Organization')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pins',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(condition=models.Q(organization=None), fields=('resource_type', 'resource_id', 'user'), name='user_pin_unique'),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, organization=None), fields=('resource_type', 'resource_id', 'organization'), name='org_pin_unique'),
        ),
    ]
