# Generated by Django 3.0.9 on 2020-12-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='pin',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
