# Generated by Django 3.0.9 on 2020-12-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20201217_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['order']},
        ),
    ]
