# Generated by Django 4.2.11 on 2024-08-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_referenced_object_uri_alter_event_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='object_uri',
            new_name='object_url',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='referenced_object_uri',
            new_name='referenced_object_url',
        ),
    ]
