# Generated by Django 4.2.11 on 2024-08-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_object_uri_event_object_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
    ]
