# Generated by Django 4.2.11 on 2024-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='referenced_object_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
