# Generated by Django 4.2.16 on 2025-09-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_referenced_object_url'),
    ]

    operations = [
        migrations.RunSQL('CREATE INDEX if not exists idx_events_object_url ON events_event (object_url);'),
        migrations.RunSQL('CREATE INDEX if not exists idx_events_referenced_object_url ON events_event (referenced_object_url);')
    ]
