# Generated by Django 3.0.7 on 2020-07-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionreference',
            unique_together={('expression', 'collection')},
        ),
    ]
