# Generated by Django 3.0.8 on 2020-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_mapping_versioned_object_id'),
        ('collections', '0003_auto_20200720_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mappings',
            field=models.ManyToManyField(blank=True, to='mappings.Mapping'),
        ),
    ]
