# Generated by Django 3.0.8 on 2020-07-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20200713_1352'),
        ('collections', '0003_auto_20200713_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='concepts',
            field=models.ManyToManyField(blank=True, null=True, to='concepts.Concept'),
        ),
    ]
