# Generated by Django 3.0.8 on 2020-07-17 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_auto_20200717_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='last_resolved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
