# Generated by Django 3.0.8 on 2020-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_auto_20200717_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='references',
            field=models.ManyToManyField(blank=True, to='collections.CollectionReference'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionreference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collectionreference',
            name='collection',
        ),
    ]
