# Generated by Django 3.0.8 on 2020-07-24 05:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_collection_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='_background_process_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
