# Generated by Django 3.0.8 on 2020-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_auto_20200718_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='collections', to='collections.CollectionReference'),
        ),
    ]
