# Generated by Django 3.0.9 on 2020-11-23 07:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0010_collection_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='identifier',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='immutable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='jurisdiction',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
