# Generated by Django 3.1.6 on 2021-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0016_collection_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='contact',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='identifier',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='jurisdiction',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
