# Generated by Django 3.1.6 on 2021-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0018_auto_20210326_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='experimental',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='locked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
