# Generated by Django 3.1.6 on 2021-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0019_auto_20210402_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='immutable',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
