# Generated by Django 3.1.8 on 2021-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0020_auto_20210411_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
