# Generated by Django 3.1.9 on 2021-06-26 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0021_collection_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionreference',
            name='last_resolved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
