# Generated by Django 3.1.12 on 2021-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0022_auto_20210626_0553'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['version'], name='collections_version_d06285_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['retired'], name='collections_retired_b74ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_latest_version'], name='collections_is_late_3141fb_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['mnemonic'], name='collections_mnemoni_645977_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['uri'], name='collections_uri_145a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-updated_at'], name='collections_updated_30bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-created_at'], name='collections_created_40f411_idx'),
        ),
    ]
