# Generated by Django 3.1.12 on 2021-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0023_auto_20210716_1341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_active'], name='collections_is_acti_b65401_idx'),
        ),
    ]
