# Generated by Django 3.2.8 on 2021-11-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0026_auto_20210914_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active_concepts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='active_mappings',
            field=models.IntegerField(default=0),
        ),
    ]
