# Generated by Django 3.2.7 on 2021-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0028_remove_expansion_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='expansion_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
