# Generated by Django 3.2.7 on 2021-10-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0026_auto_20210914_1420'),
        ('collections', '0029_collection_expansion_uri'),
    ]

    operations = [
    ]
