# Generated by Django 3.2.7 on 2021-10-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0030_merge_20211005_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansion',
            name='internal_reference_id',
        ),
    ]
