# Generated by Django 3.2.8 on 2021-11-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0027_auto_20211108_0332'),
        ('collections', '0031_remove_expansion_internal_reference_id'),
    ]

    operations = [
    ]
