# Generated by Django 3.2.8 on 2022-01-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0028_auto_20220106_0919'),
        ('collections', '0033_auto_20211208_0322'),
    ]

    operations = [
    ]
