# Generated by Django 3.2.8 on 2022-02-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0028_auto_20220203_0733'),
        ('collections', '0035_auto_20220204_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencedMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappings.mapping')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.collectionreference')),
            ],
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='_mappings',
            field=models.ManyToManyField(related_name='references', through='collections.ReferencedMapping', to='mappings.Mapping'),
        ),
    ]
