# Generated by Django 3.2.8 on 2022-02-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0037_auto_20220204_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreference',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_set', to='collections.collection'),
        ),
    ]
