# Generated by Django 3.2.8 on 2022-02-07 14:50

from django.db import migrations


def delete_dormant_references(apps, schema_editor):
    CollectionReference = apps.get_model('collections', 'CollectionReference')
    CollectionReference.objects.filter(collections__isnull=True).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0039_auto_20220204_1228'),
    ]

    operations = [
        migrations.RunPython(delete_dormant_references),
    ]
