# Generated by Django 3.2.8 on 2022-02-04 12:28

from django.db import migrations


def update_collection_reference_relations(apps, schema_editor):
    Collection = apps.get_model('collections', 'Collection')
    CollectionReference = apps.get_model('collections', 'CollectionReference')
    CollectionReference.objects.filter(collections__isnull=True).all().delete()

    for collection in Collection.objects.all():
        collection.references.update(collection_id=collection.id)


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0038_collectionreference_collection'),
    ]

    operations = [
        migrations.RunPython(update_collection_reference_relations)
    ]
