# Generated by Django 3.2.8 on 2022-02-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0040_alter_collectionreference_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='references',
        ),
    ]
