# Generated by Django 3.2.8 on 2022-02-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0042_alter_collectionreference_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
