# Generated by Django 4.0.3 on 2022-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0046_collectionreference_code_collectionreference_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
