# Generated by Django 4.0.3 on 2022-05-02 17:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collections', '0047_alter_collection_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreference',
            name='cascade',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('concepts', 'Concepts'), ('mappings', 'Mappings')], default='concepts', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='resource_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='transform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreference',
            name='valueset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
