# Generated by Django 4.0.4 on 2022-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0050_alter_collectionreference_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreference',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
