# Generated by Django 4.0.4 on 2022-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0030_source_autoid_concept_external_id_start_from_and_more'),
        ('collections', '0051_collectionreference_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='resolved_collection_versions',
            field=models.ManyToManyField(related_name='expansions_resolved_collection_versions_set', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='resolved_source_versions',
            field=models.ManyToManyField(related_name='expansions_resolved_source_versions_set', to='sources.source'),
        ),
    ]
