# Generated by Django 4.0.4 on 2022-06-27 11:06

import core.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0052_expansion_resolved_collection_versions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='canonical_url',
            field=core.common.fields.URIField(blank=True, null=True),
        ),
    ]
