# Generated by Django 4.0.6 on 2022-09-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0053_alter_collection_canonical_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='repository_type',
        ),
    ]
