# Generated by Django 4.1.1 on 2022-11-02 04:03

from django.db import migrations


def populate_extras_in_versions(apps, schema_editor):
    Collection = apps.get_model('collections', 'Collection')
    for collection in Collection.objects.filter(version='HEAD'):
        Collection.objects.filter(
            organization_id=collection.organization_id, user_id=collection.user_id, mnemonic=collection.mnemonic
        ).exclude(version='HEAD').update(extras=collection.extras)


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0054_remove_collection_repository_type'),
    ]

    operations = [
        migrations.RunPython(populate_extras_in_versions)
    ]
