# Generated by Django 4.1.7 on 2023-02-27 17:09

from django.db import migrations


def populate_custom_validation_schema_as_none_when_empty(apps, schema_editor):
    Collection = apps.get_model('collections', 'Collection')
    Collection.objects.filter(custom_validation_schema__isnull=True).update(custom_validation_schema='None')


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0055_auto_20221102_0403'),
    ]

    operations = [
        migrations.RunPython(populate_custom_validation_schema_as_none_when_empty)
    ]
