# Generated by Django 4.1.7 on 2023-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0056_auto_20230227_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='custom_validation_schema',
            field=models.CharField(choices=[('None', 'None'), ('OpenMRS', 'OpenMRS')], default='None', max_length=100),
        ),
    ]
