# Generated by Django 4.1.7 on 2023-04-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0058_remove_collection_collections_uri_145a5a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='collections_is_late_3141fb_idx',
        ),
    ]
