# Generated by Django 4.1.7 on 2023-04-13 11:13

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0059_remove_collection_collections_is_late_3141fb_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mnemonic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))]),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='mnemonic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))]),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['mnemonic'], name='coll_mnemonic_like', opclasses=['text_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='expansion',
            index=models.Index(fields=['mnemonic'], name='expansion_mnemonic_like', opclasses=['text_pattern_ops']),
        ),
    ]
