# Generated by Django 4.1.7 on 2023-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0061_remove_expansion_collection__public__ce3ef6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['uri'], name='collections_uri_145a5a_idx'),
        ),
    ]
