# Generated by Django 4.1.7 on 2023-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0062_collection_collections_uri_145a5a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
