# Generated by Django 4.2.11 on 2024-10-24 02:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0064_collection_coll_org_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='unresolved_repo_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
