# Generated by Django 4.2.11 on 2024-10-24 02:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0065_expansion_unresolved_repo_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='unresolved_repo_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
