# Generated by Django 4.2.16 on 2025-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0045_auto_20250821_1050'),
        ('collections', '0066_alter_expansion_unresolved_repo_versions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expansion',
            old_name='resolved_collection_versions',
            new_name='explicit_collection_versions',
        ),
        migrations.RenameField(
            model_name='expansion',
            old_name='resolved_source_versions',
            new_name='explicit_source_versions',
        ),
        migrations.AlterField(
            model_name='expansion',
            name='explicit_collection_versions',
            field=models.ManyToManyField(
                to='collections.collection',
                related_name='expansions_explicit_collection_versions_set',
            ),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='explicit_source_versions',
            field=models.ManyToManyField(
                to='sources.source',
                related_name='expansions_explicit_source_versions_set',
            ),
        ),
        migrations.AddField(
            model_name='expansion',
            name='evaluated_collection_versions',
            field=models.ManyToManyField(related_name='expansions_evaluated_collection_versions_set', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='evaluated_source_versions',
            field=models.ManyToManyField(related_name='expansions_evaluated_source_versions_set', to='sources.source'),
        ),
    ]
