# Generated by Django 4.2.16 on 2025-12-22 16:05

from django.db import migrations


def update_expansion_with_legacy_flag(apps, schema_editor):
    Expansion = apps.get_model('collections', 'Expansion')
    Expansion.objects.update(extras={'__legacy_expansion': True})


class Migration(migrations.Migration):
    dependencies = [
        ('collections', '0067_remove_expansion_resolved_collection_versions_and_more'),
    ]

    operations = [
        migrations.RunPython(update_expansion_with_legacy_flag),
    ]
