# Generated by Django 4.2.16 on 2026-01-08 12:05

from django.db import migrations

from core.collections.models import default_expansion_parameters


def expansion_parameters_empty_from_default(apps, schema_editor):
    Expansion = apps.get_model('collections', 'Expansion')
    default_parameters = default_expansion_parameters()
    for expansion in Expansion.objects.filter(parameters__isnull=False).exclude(parameters={}):
        update = False
        for key, value in expansion.parameters.copy().items():
            if key in default_parameters and value == default_parameters[key]:
                del expansion.parameters[key]
                update = True
        if update:
            expansion.save(update_fields=['parameters'])


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0068_auto_20251222_1605'),
    ]

    operations = [
        migrations.RunPython(expansion_parameters_empty_from_default),
    ]
