# Generated by Django 4.2.16 on 2026-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0069_auto_20260108_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
