# Generated by Django 5.2.17 on 2026-09-25 01:52

from django.db import migrations, models


# 'Edit' is retired: every public-Edit resource becomes public-View.
def retire_public_edit_access(apps, schema_editor):  # pylint: disable=unused-argument
    apps.get_model('collections', 'Collection').objects.filter(public_access__iexact='Edit').update(public_access='View')
    apps.get_model('collections', 'Expansion').objects.filter(public_access__iexact='Edit').update(public_access='View')


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0070_alter_expansion_parameters'),
    ]

    operations = [
        migrations.RunPython(retire_public_edit_access, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='collection',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
    ]
