# Generated by Django 3.0.7 on 2020-06-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(to='orgs.Organization'),
        ),
    ]
