# Generated by Django 3.0.9 on 2020-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20200720_1450'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(related_name='users', to='orgs.Organization'),
        ),
    ]
