# Generated by Django 3.0.7 on 2020-06-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mnemonic',
        ),
    ]
