# Generated by Django 3.0.9 on 2020-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20200720_1450'),
        ('users', '0002_auto_20200821_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(related_name='members', to='orgs.Organization'),
        ),
    ]
