# Generated by Django 3.0.9 on 2020-12-15 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_logo_path'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_userprofile_logo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pins',
                'ordering': ['created_at'],
                'unique_together': {('resource_type', 'resource_id', 'user', 'organization')},
            },
        ),
    ]
