# Generated by Django 3.0.9 on 2020-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pinneditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pinneditem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pinneditem',
            constraint=models.UniqueConstraint(condition=models.Q(organization=None), fields=('resource_type', 'resource_id', 'user'), name='user_pin_unique'),
        ),
        migrations.AddConstraint(
            model_name='pinneditem',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, organization=None), fields=('resource_type', 'resource_id', 'user', 'organization'), name='user_org_pin_unique'),
        ),
    ]
