# Generated by Django 3.0.9 on 2020-12-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201215_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedItem',
        ),
    ]
