# Generated by Django 3.1.12 on 2021-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210716_1341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='user_profil_is_acti_44246c_idx'),
        ),
    ]
