# Generated by Django 3.2.7 on 2021-09-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210720_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='internal_reference_id',
        ),
    ]
