# Generated by Django 4.1.7 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
