# Generated by Django 4.2.4 on 2023-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
