# Generated by Django 4.2.11 on 2024-08-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_followed_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followed',
            old_name='followed_id',
            new_name='following_id',
        ),
        migrations.RenameField(
            model_name='followed',
            old_name='followed_type',
            new_name='following_type',
        ),
    ]
