# Generated by Django 4.2.11 on 2024-08-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0025_rename_followed_id_followed_following_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followed',
            new_name='Follow',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
