# Generated by Django 4.2.11 on 2024-08-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0026_rename_followed_follow_alter_follow_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following_id', 'following_type')},
        ),
    ]
