# Generated by Django 4.2.16 on 2025-03-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userratelimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratelimit',
            old_name='employee',
            new_name='user',
        ),
    ]
