# Generated by Django 4.2.16 on 2025-03-06 11:50

from django.db import migrations


def populate_api_rate_limit(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserRateLimit = apps.get_model('users', 'UserRateLimit')
    rate_limits = [
        UserRateLimit(user=user) for user in UserProfile.objects.filter()
    ]
    UserRateLimit.objects.bulk_create(rate_limits)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_employee_userratelimit_user'),
    ]

    operations = [
        migrations.RunPython(populate_api_rate_limit)
    ]
