# Generated by Django 4.2.16 on 2025-03-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20250306_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratelimit',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='userratelimit',
            name='public_access',
        ),
        migrations.RemoveField(
            model_name='userratelimit',
            name='uri',
        ),
    ]
