# Generated by Django 4.2.16 on 2025-03-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_userratelimit_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratelimit',
            name='rate_plan',
            field=models.CharField(choices=[('lite', 'lite'), ('guest', 'guest')], default='lite', max_length=100),
        ),
    ]
