# Generated by Django 4.2.16 on 2025-11-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_userratelimit_rate_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRateLimit',
        ),
    ]
