# Generated by Django 5.2.17 on 2026-09-25 01:54

from django.db import migrations, models


# 'Edit' is retired: every public-Edit resource becomes public-View.
def retire_public_edit_access(apps, schema_editor):  # pylint: disable=unused-argument
    apps.get_model('users', 'UserProfile').objects.filter(public_access__iexact='Edit').update(public_access='View')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_delete_userratelimit'),
    ]

    operations = [
        migrations.RunPython(retire_public_edit_access, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
    ]
