# Generated by Django 3.0.8 on 2020-07-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_mapping_versioned_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='versioned_object_id',
        ),
        migrations.AddField(
            model_name='mapping',
            name='versioned_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mappings.Mapping'),
        ),
    ]
