# Generated by Django 3.0.8 on 2020-07-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0004_auto_20200722_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='versioned_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions_set', to='mappings.Mapping'),
        ),
    ]
