# Generated by Django 3.0.9 on 2020-10-05 06:49

import django.core.validators
from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20200729_0718'),
        ('mappings', '0005_auto_20200722_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='mnemonic',
            field=models.CharField(default=uuid.uuid4, max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))]),
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('mnemonic', 'version', 'parent')},
        ),
    ]
