# Generated by Django 3.0.9 on 2021-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0007_auto_20201005_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='from_concept_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='from_concept_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='from_source_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='from_source_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='to_source_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='to_source_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
