# Generated by Django 3.0.9 on 2021-01-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_auto_20200923_0246'),
        ('sources', '0009_source_logo_path'),
        ('mappings', '0009_auto_20210104_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='from_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings_from', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='from_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings_from', to='concepts.Concept'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='to_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings_to', to='concepts.Concept'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='to_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings_to', to='sources.Source'),
        ),
    ]
