# Generated by Django 3.0.9 on 2021-01-06 07:18

from django.db import migrations
from pydash import get


def resolve_fields_from_relations(apps, schema_editor):
    Mapping = apps.get_model('mappings', 'Mapping')
    for mapping in Mapping.objects.select_related('from_concept__parent', 'to_concept__parent', 'to_source', 'from_source').all():
        save = False
        if not mapping.from_concept_code and mapping.from_concept_id:
            mapping.from_concept_code = get(mapping, 'from_concept.mnemonic')
            save = True
        if not mapping.from_source_url and mapping.from_concept_id:
            mapping.from_source_url = mapping.from_concept.parent.uri
            save = True
        if not mapping.to_concept_code and mapping.to_concept_id:
            mapping.to_concept_code = get(mapping, 'to_concept.mnemonic')
            save = True
        if not mapping.to_source_url and (mapping.to_source_id or mapping.to_concept_id):
            mapping.to_source_url = get(mapping, 'to_source.uri') or get(mapping, 'to_concept.parent.uri')
            save = True
        if not mapping.to_source_id and mapping.to_concept_id:
            mapping.to_source_id = get(mapping, 'to_concept.parent_id')
            save = True
        if not mapping.from_source_id and mapping.from_concept_id:
            mapping.from_source_id = get(mapping, 'from_concept.parent_id')
            save = True

        if save:
            mapping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0010_auto_20210106_0718'),
    ]

    operations = [
        migrations.RunPython(resolve_fields_from_relations)
    ]
