# Generated by Django 3.0.9 on 2021-01-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_source_logo_path'),
        ('mappings', '0011_auto_20210106_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_set', to='sources.Source'),
        ),
    ]
