# Generated by Django 3.0.9 on 2021-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0012_auto_20210106_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='from_concept_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='from_source_url',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='map_type',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='to_concept_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='to_source_url',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='uri',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
