# Generated by Django 3.1.6 on 2021-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0014_auto_20210326_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='released',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
