# Generated by Django 3.1.9 on 2021-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0015_auto_20210326_1029'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['-updated_at'], name='mappings_updated_bbec57_idx'),
        ),
    ]
