# Generated by Django 3.1.12 on 2021-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0016_auto_20210709_1238'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['version'], name='mappings_version_35582f_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['retired'], name='mappings_retired_49a606_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['is_latest_version'], name='mappings_is_late_515fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['mnemonic'], name='mappings_mnemoni_b79efa_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['uri'], name='mappings_uri_f7a346_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['-created_at'], name='mappings_created_c41e8e_idx'),
        ),
    ]
