# Generated by Django 3.1.12 on 2021-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0017_auto_20210716_1341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['is_active'], name='mappings_is_acti_71d019_idx'),
        ),
    ]
