# Generated by Django 3.1.12 on 2021-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0018_auto_20210716_1353'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['public_access'], name='mappings_public__c996b2_idx'),
        ),
    ]
