# Generated by Django 3.1.12 on 2021-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0019_auto_20210720_1000'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['is_active', 'retired', 'is_latest_version', 'public_access'], name='mappings_is_acti_ccfa00_idx'),
        ),
    ]
