# Generated by Django 3.2.7 on 2021-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0021_remove_mapping_internal_reference_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_is_acti_ccfa00_idx',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['is_active', 'retired', 'is_latest_version', 'public_access', '-updated_at'], name='mappings_is_acti_3af71d_idx'),
        ),
    ]
