# Generated by Django 3.2.7 on 2021-10-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0022_auto_20211012_1107'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_is_acti_3af71d_idx',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='mappings_updated_4589ad_idx'),
        ),
    ]
