# Generated by Django 3.2.8 on 2021-11-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0020_auto_20210811_1058'),
        ('mappings', '0025_mapping__counted'),
    ]

    operations = [
    ]
