# Generated by Django 3.2.8 on 2022-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0027_remove_mapping_mappings_is_acti_ccfa00_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['is_active'], name='mappings_all_for_count'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['-updated_at'], name='mappings_all_for_sort'),
        ),
    ]
