# Generated by Django 4.0.3 on 2022-04-12 07:19

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0031_alter_mapping_created_by_alter_mapping_updated_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='mappings_public_cond2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', django.db.models.expressions.F('versioned_object_id')), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='mappings_ver_public_cond2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['parent_id'], name='mappings_all_for_count2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', django.db.models.expressions.F('versioned_object_id'))), fields=['parent_id'], name='mappings_ver_all_for_count2'),
        ),
    ]
