# Generated by Django 4.0.4 on 2022-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0032_mapping_mappings_public_cond2_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='mappings_ver_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['public_access'], name='mappings_ver_public'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['is_active'], name='mappings_ver_for_count'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['-updated_at'], name='mappings_ver_for_sort'),
        ),
    ]
