# Generated by Django 4.1.7 on 2023-03-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0036_mapping_mappings_all_for_count3'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count3',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['parent_id', '-updated_at', 'is_active', 'retired', 'id', 'versioned_object_id'], name='mappings_all_for_count3'),
        ),
    ]
