# Generated by Django 4.1.7 on 2023-03-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0037_remove_mapping_mappings_all_for_count3_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('retired', True), ('id', models.F('versioned_object_id'))), fields=['parent_id'], name='mapping_retired_count_idx'),
        ),
    ]
