# Generated by Django 4.1.7 on 2023-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0038_mapping_mapping_retired_count_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_updated_6490d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_sort_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_public_conditional',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_public',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_sort',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_for_sort',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_public_cond',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_sort',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_sort_2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count3',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mapping_retired_count_idx',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='mappings_updated_4589ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='mappings_ver_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id')), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='mappings_vers_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['public_access'], name='mappings_public_conditional'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['public_access'], name='mappings_ver_public'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id')), models.Q(('public_access', 'None'), _negated=True)), fields=['public_access'], name='mappings_ver_public_cond'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='mappings_public_cond2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id')), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='mappings_ver_public_cond2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['is_active'], name='mappings_all_for_count'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['is_active'], name='mappings_ver_for_count'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['is_active'], name='mappings_ver_all_for_count'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['parent_id'], name='mappings_all_for_count2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['parent_id'], name='mappings_ver_all_for_count2'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['-updated_at'], name='mappings_all_for_sort'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['-updated_at'], name='mappings_ver_for_sort'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['-updated_at'], name='mappings_ver_all_for_sort'),
        ),
    ]
