# Generated by Django 4.1.7 on 2023-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0039_remove_mapping_mappings_updated_6490d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_updated_4589ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_updated_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_vers_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_public_conditional',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_public',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_public_cond',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_public_cond2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_public_cond2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_count',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_count2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_count2',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_all_for_sort',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_for_sort',
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_ver_all_for_sort',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['-updated_at', 'public_access', 'is_latest_version'], name='mappings_up_pub_latest'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['-updated_at', 'public_access'], name='mappings_head_up_pub'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['-updated_at', 'is_latest_version'], name='mappings_up_latest'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['public_access', 'is_latest_version'], name='mappings_pub_latest'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['public_access'], name='mappings_head_pub'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['parent_id', 'public_access', 'is_latest_version'], name='mappings_parent_pub_latest'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', models.F('versioned_object_id'))), fields=['parent_id', 'public_access'], name='mappings_head_parent_pub'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['is_latest_version', 'parent_id'], name='mappings_latest_parent'),
        ),
    ]
