# Generated by Django 4.1.7 on 2023-04-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0042_remove_mapping_mappings_version_35582f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_is_late_515fbe_idx',
        ),
    ]
