# Generated by Django 4.1.7 on 2023-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0043_remove_mapping_mappings_is_late_515fbe_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='map_type',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['map_type'], name='mappings_map_type_like', opclasses=['text_pattern_ops']),
        ),
    ]
