# Generated by Django 4.1.7 on 2023-04-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0044_alter_mapping_map_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='mappings_public__c996b2_idx',
        ),
    ]
