# Generated by Django 4.1.7 on 2023-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0045_remove_mapping_mappings_public__c996b2_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['uri'], name='mappings_uri_f7a346_idx'),
        ),
    ]
