# Generated by Django 4.1.7 on 2023-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0046_mapping_mappings_uri_f7a346_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
