# Generated by Django 4.2.4 on 2024-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0053_remove_mapping_repo_version_mappings_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapping',
            name='repo_version_mappings',
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['id', '-updated_at'], name='repo_version_mappings'),
        ),
    ]
