# Generated by Django 4.2.16 on 2025-02-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0054_remove_mapping_repo_version_mappings_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            'create index if not exists mappings_repo_list_idx on mappings(parent_id, updated_at desc) '
            'where not retired and is_active and id = versioned_object_id;'
        )
    ]
