# Generated by Django 4.2.16 on 2025-02-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0055_auto_20250224_1004'),
    ]

    operations = [
        migrations.RunSQL('create index if not exists mappings_updated_active_idx on mappings(updated_at desc) where not retired and is_active;')  # for repo version mappings
    ]
