# Generated by Django 5.1.15 on 2026-05-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0057_mappings_sources_source_mapping_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='retire_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
