# Generated by Django 5.2.17 on 2026-09-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0059_mapping_head_parent_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
    ]
