# Generated by Django 4.2.4 on 2024-02-20 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('args', models.JSONField(blank=True, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('REVOKED', 'REVOKED'), ('RECEIVED', 'RECEIVED'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY')], default='PENDING', max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('retry', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'celery_tasks',
            },
        ),
    ]
