# Generated by Django 4.2.4 on 2024-02-20 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTask',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('args', models.JSONField(blank=True, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('STARTED', 'STARTED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('RECEIVED', 'RECEIVED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('retry', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'celery_tasks',
            },
        ),
    ]
