# Generated by Django 4.2.4 on 2024-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_delete_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=255),
        ),
    ]
