# Generated by Django 4.2.4 on 2024-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
