# Generated by Django 4.2.4 on 2024-02-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='queue',
        ),
    ]
