# Generated by Django 4.2.4 on 2024-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_created_at_task_finished_at_task_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue',
            field=models.TextField(default='default'),
        ),
    ]
