# Generated by Django 4.2.4 on 2024-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
