# Generated by Django 4.2.4 on 2024-03-05 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='children',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
