# Generated by Django 4.2.4 on 2024-04-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='args',
        ),
    ]
