# Generated by Django 4.2.11 on 2024-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
