# Generated by Django 5.2.17 on 2026-09-21 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('map_projects', '0038_automatchrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'capabilities',
            },
        ),
        migrations.CreateModel(
            name='GroupCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_capabilities', to='capabilities.capability')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='auth.group')),
            ],
            options={
                'db_table': 'group_capabilities',
                'unique_together': {('group', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.IntegerField(default=0)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='capabilities.capability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_counters',
                'unique_together': {('user', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=1)),
                ('action', models.CharField(blank=True, default='', max_length=100)),
                ('algorithm', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='capabilities.capability')),
                ('map_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='map_projects.mapproject')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='map_projects.automatchrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_events',
                'indexes': [models.Index(fields=['user', 'capability'], name='usage_event_user_id_c77c87_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCapabilityOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='capabilities.capability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_capability_overrides',
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
