# Generated by Django 5.2.17 on 2026-09-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'capability', 'idempotency_key'), name='usage_events_unique_idempotency_key'),
        ),
    ]
