# Generated by Django 3.0.8 on 2020-07-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0001_initial'),
        ('orgs', '0002_auto_20200717_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(default='b64ce2cd-36d7-4b67-b2ec-d6e69a24c7a9', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sources_source_related_created_by', related_query_name='sources_sources_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_by',
            field=models.ForeignKey(default='b64ce2cd-36d7-4b67-b2ec-d6e69a24c7a9', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sources_source_related_updated_by', related_query_name='sources_sources_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(user=None), fields=('mnemonic', 'version', 'organization'), name='org_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(organization=None), fields=('mnemonic', 'version', 'user'), name='user_source_unique'),
        ),
    ]
