# Generated by Django 3.0.8 on 2020-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20200720_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
