# Generated by Django 3.0.7 on 2020-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20200622_0513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(user=None), fields=('mnemonic', 'version', 'organization'), name='org_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(organization=None), fields=('mnemonic', 'version', 'user'), name='user_source_unique'),
        ),
    ]
