# Generated by Django 3.0.8 on 2020-07-24 05:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20200721_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='_background_process_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
