# Generated by Django 3.0.7 on 2020-07-01 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20200630_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='active_concepts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='active_mappings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='last_child_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='source',
            name='last_concept_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_mapping_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
