# Generated by Django 3.0.7 on 2020-07-06 10:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20200701_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='mnemonic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))]),
        ),
    ]
