# Generated by Django 3.0.8 on 2020-07-29 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20200724_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='_background_process_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
