# Generated by Django 3.0.9 on 2020-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20200729_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
