# Generated by Django 3.0.9 on 2020-12-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20201123_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
