# Generated by Django 3.0.9 on 2021-01-15 08:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_source_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='mnemonic',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@]+$'))]),
        ),
        migrations.AlterField(
            model_name='source',
            name='uri',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
