# Generated by Django 3.0.9 on 2021-01-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_auto_20210115_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='active_concepts',
        ),
        migrations.RemoveField(
            model_name='source',
            name='active_mappings',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_child_update',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_concept_update',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_mapping_update',
        ),
    ]
