# Generated by Django 3.1.6 on 2021-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_auto_20210326_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='case_sensitive',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='collection_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='compositional',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='experimental',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='hierarchy_meaning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='version_needed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
