# Generated by Django 3.1.8 on 2021-04-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_source_hierarchy_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='hierarchy_meaning',
            field=models.CharField(blank=True, choices=[('grouped-by', 'grouped-by'), ('is-a', 'is-a'), ('part-of', 'part-of'), ('classified-with', 'classified-with')], max_length=50, null=True),
        ),
    ]
