# Generated by Django 3.1.8 on 2021-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0018_auto_20210417_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
