# Generated by Django 3.1.12 on 2021-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_source_meta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['version'], name='sources_version_fd6677_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['retired'], name='sources_retired_b2a167_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_latest_version'], name='sources_is_late_672be3_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['mnemonic'], name='sources_mnemoni_56cf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['uri'], name='sources_uri_93503a_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['-updated_at'], name='sources_updated_b256b3_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['-created_at'], name='sources_created_9c2056_idx'),
        ),
    ]
