# Generated by Django 3.1.12 on 2021-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_auto_20210716_1341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active'], name='sources_is_acti_267b08_idx'),
        ),
    ]
