# Generated by Django 3.1.12 on 2021-07-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_auto_20210716_1353'),
    ]

    operations = [
        migrations.RunSQL(
            sql=r'CREATE INDEX "sources_mnemoni_upper_55439b_idx" ON "sources" (UPPER("mnemonic"));',
            reverse_sql=r'DROP INDEX "sources_mnemoni_upper_55439b_idx";'
        ),
    ]
