# Generated by Django 3.1.12 on 2021-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_auto_20210720_0835'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['public_access'], name='sources_public__2da2df_idx'),
        ),
    ]
