# Generated by Django 3.2.8 on 2021-11-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_remove_source_internal_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='active_concepts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='active_mappings',
            field=models.IntegerField(default=0),
        ),
    ]
