# Generated by Django 4.0.3 on 2022-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_alter_source_created_by_alter_source_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
