# Generated by Django 4.0.4 on 2022-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0028_alter_source_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='autoid_concept_external_id',
            field=models.CharField(blank=True, choices=[('sequential', 'Sequential'), ('uuid', 'UUID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='autoid_concept_mnemonic',
            field=models.CharField(blank=True, choices=[('sequential', 'Sequential'), ('uuid', 'UUID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='autoid_mapping_external_id',
            field=models.CharField(blank=True, choices=[('sequential', 'Sequential'), ('uuid', 'UUID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='autoid_mapping_mnemonic',
            field=models.CharField(blank=True, choices=[('sequential', 'Sequential'), ('uuid', 'UUID')], default='sequential', max_length=10, null=True),
        ),
    ]
