# Generated by Django 4.1.1 on 2022-11-02 04:03

from django.db import migrations


def populate_extras_in_versions(apps, schema_editor):
    Source = apps.get_model('sources', 'Source')
    for source in Source.objects.filter(version='HEAD'):
        Source.objects.filter(
            organization_id=source.organization_id, user_id=source.user_id, mnemonic=source.mnemonic
        ).exclude(version='HEAD').update(extras=source.extras)


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0031_alter_source_canonical_url'),
    ]

    operations = [
        migrations.RunPython(populate_extras_in_versions)
    ]
