# Generated by Django 4.1.7 on 2023-02-27 17:05

from django.db import migrations


def populate_custom_validation_schema_as_none_when_empty(apps, schema_editor):
    Source = apps.get_model('sources', 'Source')
    Source.objects.filter(custom_validation_schema__isnull=True).update(custom_validation_schema='None')


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0032_auto_20221102_0403'),
    ]

    operations = [
        migrations.RunPython(populate_custom_validation_schema_as_none_when_empty)
    ]
