# Generated by Django 4.1.7 on 2023-02-27 17:19

from django.db import migrations


def update_hierarchy_meaning(apps, schema_editor):
    Source = apps.get_model('sources', 'Source')
    Source.objects.filter(hierarchy_meaning='').update(hierarchy_meaning=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_alter_source_custom_validation_schema'),
    ]

    operations = [
        migrations.RunPython(update_hierarchy_meaning)
    ]
