# Generated by Django 4.1.7 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0035_auto_20230227_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
