# Generated by Django 4.1.7 on 2023-04-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0036_alter_source_uri'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='source',
            name='sources_is_late_672be3_idx',
        ),
    ]
