# Generated by Django 4.1.7 on 2023-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0038_alter_source_mnemonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
