# Generated by Django 4.2.4 on 2023-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0039_source_checksums'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='autoid_concept_description_external_id',
            field=models.CharField(blank=True, choices=[('uuid', 'UUID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='autoid_concept_name_external_id',
            field=models.CharField(blank=True, choices=[('uuid', 'UUID')], max_length=10, null=True),
        ),
    ]
