# Generated by Django 4.2.4 on 2023-12-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0040_source_autoid_concept_description_external_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(condition=models.Q(('is_active', True), ('released', True), ('user__isnull', True)), fields=['mnemonic', 'organization', '-created_at'], name='source_org_released'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(condition=models.Q(('is_active', True), ('organization__isnull', True), ('released', True)), fields=['mnemonic', 'user', '-created_at'], name='source_user_released'),
        ),
    ]
