# Generated by Django 4.2.16 on 2025-05-22 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0042_alter_source_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='source',
            name='properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
