# Generated by Django 4.2.16 on 2025-08-07 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0043_source_filters_source_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='match_algorithms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
