# Generated by Django 4.2.16 on 2025-08-21 10:50

from django.db import migrations

def update_source_properties(apps, schema_editor):
    Source = apps.get_model('sources', 'Source')
    for source in Source.objects.exclude(properties=[]):
        if source.properties:
            ordered = []
            new_properties = []
            for prop in source.properties.copy():
                if prop.get('code') and prop.get('include_in_concept_summary') is True:
                    ordered.append(prop['code'])
                    prop.pop('include_in_concept_summary')
                new_properties.append(prop)
            if ordered:
                source.properties = new_properties
                source.meta = source.meta or {}
                source.meta['display'] = {'concept_summary_properties': ordered}
                source.save()



class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0044_source_match_algorithms'),
    ]

    operations = [
        migrations.RunPython(update_source_properties)
    ]


