# Generated by Django 5.2.17 on 2026-09-25 01:53

from django.db import migrations, models


# 'Edit' is retired: public-Edit sources, and their concepts and mappings, become public-View.
def retire_public_edit_access(apps, schema_editor):  # pylint: disable=unused-argument
    Source = apps.get_model('sources', 'Source')
    source_ids = list(Source.objects.filter(public_access__iexact='Edit').values_list('id', flat=True))
    if not source_ids:
        return
    for model in [apps.get_model('concepts', 'Concept'), apps.get_model('mappings', 'Mapping')]:
        model.objects.filter(parent_id__in=source_ids, public_access__iexact='Edit').update(public_access='View')
    Source.objects.filter(id__in=source_ids).update(public_access='View')


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0045_auto_20250821_1050'),
        ('concepts', '0088_retire_public_edit_access'),
        ('mappings', '0060_retire_public_edit_access'),
    ]

    operations = [
        migrations.RunPython(retire_public_edit_access, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='source',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
    ]
