# Generated by Django 3.0.7 on 2020-06-17 04:14

import re

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('locale', models.TextField()),
                ('locale_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'localized_texts',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_access', models.CharField(blank=True, choices=[('View', 'View'), ('Edit', 'Edit'), ('None', 'None')], default='View', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('mnemonic', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_]+$'))])),
                ('version', models.CharField(max_length=255)),
                ('released', models.NullBooleanField(default=False)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('full_name', models.TextField(blank=True, null=True)),
                ('default_locale', models.TextField(blank=True, default='en')),
                ('supported_locales', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('website', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('concept_class', models.TextField()),
                ('datatype', models.TextField()),
                ('retired', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_concept_related_created_by', related_query_name='concepts_concepts_created_by', to=settings.AUTH_USER_MODEL)),
                ('descriptions', models.ManyToManyField(blank=True, null=True, related_name='description_locales', to='concepts.LocalizedText')),
                ('names', models.ManyToManyField(blank=True, null=True, related_name='name_locales', to='concepts.LocalizedText')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_set', to='sources.Source')),
                ('sources', models.ManyToManyField(blank=True, null=True, related_name='concepts', to='sources.Source')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_concept_related_updated_by', related_query_name='concepts_concepts_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'concepts',
            },
        ),
    ]
