# Generated by Django 3.0.8 on 2020-07-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='created_by',
            field=models.ForeignKey(default='b64ce2cd-36d7-4b67-b2ec-d6e69a24c7a9', on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_concept_related_created_by', related_query_name='concepts_concepts_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='descriptions',
            field=models.ManyToManyField(related_name='description_locales', to='concepts.LocalizedText'),
        ),
        migrations.AddField(
            model_name='concept',
            name='names',
            field=models.ManyToManyField(related_name='name_locales', to='concepts.LocalizedText'),
        ),
        migrations.AddField(
            model_name='concept',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_set', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='concept',
            name='sources',
            field=models.ManyToManyField(related_name='concepts', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='concept',
            name='updated_by',
            field=models.ForeignKey(default='b64ce2cd-36d7-4b67-b2ec-d6e69a24c7a9', on_delete=django.db.models.deletion.DO_NOTHING, related_name='concepts_concept_related_updated_by', related_query_name='concepts_concepts_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('mnemonic', 'version', 'parent')},
        ),
    ]
