# Generated by Django 3.0.7 on 2020-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20200617_0500'),
        ('concepts', '0002_auto_20200617_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='descriptions',
            field=models.ManyToManyField(related_name='description_locales', to='concepts.LocalizedText'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='names',
            field=models.ManyToManyField(related_name='name_locales', to='concepts.LocalizedText'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='sources',
            field=models.ManyToManyField(related_name='concepts', to='sources.Source'),
        ),
    ]
