# Generated by Django 3.0.8 on 2020-07-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20200720_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='versioned_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='concepts.Concept'),
        ),
    ]
