# Generated by Django 3.1.8 on 2021-04-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0009_auto_20210414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalconcepts',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='concepts.concept'),
        ),
        migrations.AlterField(
            model_name='hierarchicalconcepts',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='concepts.concept'),
        ),
    ]
