# Generated by Django 3.1.8 on 2021-05-21 05:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0009_auto_20210414_1020_squashed_0012_auto_20210414_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='mnemonic',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@\\+\\%]+$'))]),
        ),
    ]
