# Generated by Django 3.1.8 on 2021-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0010_auto_20210414_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='parent_concepts',
            field=models.ManyToManyField(related_name='child_concepts', through='concepts.HierarchicalConcepts', to='concepts.Concept'),
        ),
    ]
