# Generated by Django 3.1.9 on 2021-06-17 12:29

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0010_auto_20210521_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='mnemonic',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@\\+\\% ]+$'))]),
        ),
    ]
