# Generated by Django 3.1.8 on 2021-04-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0011_auto_20210414_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalconcepts',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_parent', to='concepts.concept'),
        ),
        migrations.AlterField(
            model_name='hierarchicalconcepts',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child', to='concepts.concept'),
        ),
    ]
