# Generated by Django 3.1.12 on 2021-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0013_auto_20210709_1237'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['version'], name='concepts_version_82ecf4_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['retired'], name='concepts_retired_5eb738_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['is_latest_version'], name='concepts_is_late_2ce198_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['mnemonic'], name='concepts_mnemoni_d2a79d_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['uri'], name='concepts_uri_3d0589_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['-created_at'], name='concepts_created_76effb_idx'),
        ),
    ]
