# Generated by Django 3.1.12 on 2021-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0016_auto_20210720_0902'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['public_access'], name='concepts_public__932f92_idx'),
        ),
    ]
