# Generated by Django 3.1.9 on 2021-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0017_auto_20210720_1000'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['is_active', 'retired', 'is_latest_version', 'public_access'], name='concepts_is_acti_7190c6_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=models.Index(fields=['created_at'], name='localized_t_created_4a5dc0_idx'),
        ),
    ]
