# Generated by Django 3.1.9 on 2021-08-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0018_auto_20210804_0957'),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"UPDATE localized_texts SET type='FULLY_SPECIFIED' WHERE type IN "
                r"('Fully Specified','Fully_Specified','fully_specified',"
                r"'fully specified','full-specified','FULLY-SPECIFIED');",
        ),
    ]
