# Generated by Django 3.2.7 on 2021-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0019_auto_20210914_1420'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_is_acti_7190c6_idx',
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['is_active', 'retired', 'is_latest_version', 'public_access', 'updated_at'], name='concepts_is_acti_ee42ab_idx'),
        ),
    ]
