# Generated by Django 3.2.8 on 2021-11-09 10:14

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0023_concept_concepts_public_conditional'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='concept',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('is_latest_version', True)), fields=['uri', 'id'], name='concepts_uri_trgm_id_gin_idx', opclasses=['gin_trgm_ops', 'int8_ops']),
        ),
    ]
