# Generated by Django 3.2.8 on 2021-11-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0024_concept_concepts_uri_trgm_id_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='_counted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
