# Generated by Django 3.2.8 on 2021-11-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0018_auto_20210804_0957'),
        ('concepts', '0025_concept__counted'),
    ]

    operations = [
    ]
