# Generated by Django 4.0.3 on 2022-04-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concepts', '0030_auto_20220323_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_created_by', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concept',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_updated_by', related_query_name='%(app_label)s_%(class)ss_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True)), fields=['parent_id'], name='concepts_all_for_count2'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', django.db.models.expressions.F('versioned_object_id')), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='concepts_ver_public_cond2'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('id', django.db.models.expressions.F('versioned_object_id'))), fields=['parent_id'], name='concepts_ver_all_for_count2'),
        ),
    ]
