# Generated by Django 4.0.3 on 2022-04-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0031_alter_concept_created_by_alter_concept_updated_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['parent_id'], name='concepts_public_cond'),
        ),
    ]
