# Generated by Django 4.0.4 on 2022-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0032_concept_concepts_public_cond'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_updated_6490d8_idx',
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='concepts_updated_6490d8_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), ('is_latest_version', True), models.Q(('public_access', 'None'), _negated=True)), fields=['-updated_at'], name='concepts_ver_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False), models.Q(('public_access', 'None'), _negated=True)), fields=['public_access'], name='concepts_ver_public'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['-updated_at'], name='concepts_ver_all_for_sort_2'),
        ),
    ]
