# Generated by Django 4.0.4 on 2022-06-27 12:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0034_concept_concepts_ver_for_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_name_9b0703_idx',
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='localized_t_name_039daa_hash'),
        ),
    ]
