# Generated by Django 4.1.1 on 2022-11-21 11:13

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0035_remove_localizedtext_localized_t_name_9b0703_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptDescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('locale', models.TextField()),
                ('locale_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.concept')),
            ],
            options={
                'db_table': 'concept_descriptions',
            },
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='concept_des_name_c78c88_hash'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['type'], name='concept_des_type_8be5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['locale'], name='concept_des_locale_e8d16e_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['locale_preferred'], name='concept_des_locale__4f2050_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['created_at'], name='concept_des_created_68d73f_idx'),
        ),
    ]
