# Generated by Django 4.1.1 on 2022-11-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0036_conceptdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedtext',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concepts.concept'),
        ),
    ]
