# Generated by Django 4.1.1 on 2022-11-22 05:22

from django.db import migrations, connection


def populate_concept_descriptions(apps, schema_editor):
    import time
    start = time.time()
    """
    1. Populates new concept_descriptions table from localized_texts table using many-to-many concepts_descriptions.
    2. Count of concepts_descriptions (old) and concept_descriptions (new) should be same after this migration.
    """
    with connection.cursor() as cursor:
        cursor.execute("""select concept_id, localizedtext_id from concepts_descriptions;""")
        rows = cursor.fetchall()

        statement = "insert into concept_descriptions(concept_id, external_id, name, type, locale, locale_preferred, created_at) values "
        for row in rows:
            cursor.execute(
                "select external_id, name, type, locale, locale_preferred, created_at from localized_texts where id = %s",
                [row[1]]
            )
            locale = cursor.fetchone()
            name = locale[1].replace("'", "''")
            statement += f"({row[0]}, '{locale[0]}', '{name}', '{locale[2]}', '{locale[3]}', {locale[4]}, '{locale[5]}'),"
        if statement.endswith(','):
            statement = statement[:-1] + ';'
        cursor.execute(statement)

    print('Time: ', time.time() - start)


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0037_localizedtext_concept'),
    ]

    operations = [
        migrations.RunPython(populate_concept_descriptions)
    ]
