# Generated by Django 4.1.1 on 2022-12-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0040_auto_20221122_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='descriptions',
            new_name='descriptions_old',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='names',
            new_name='names_old',
        ),
    ]
