# Generated by Django 4.1.1 on 2022-12-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0042_alter_conceptdescription_concept_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_type_1a9d65_idx',
        ),
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_locale_d5efa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_locale__f23c8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_created_4a5dc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='localizedtext',
            name='localized_t_name_039daa_hash',
        ),
        migrations.AlterModelTable(
            name='localizedtext',
            table='concept_names',
        ),
    ]
