# Generated by Django 4.1.1 on 2022-12-05 10:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0043_remove_localizedtext_localized_t_type_1a9d65_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='localizedtext',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='concept_nam_name_05c19d_hash'),
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=models.Index(fields=['type'], name='concept_nam_type_acb6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=models.Index(fields=['locale'], name='concept_nam_locale_b67794_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=models.Index(fields=['locale_preferred'], name='concept_nam_locale__931ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedtext',
            index=models.Index(fields=['created_at'], name='concept_nam_created_12e24d_idx'),
        ),
    ]
