# Generated by Django 4.1.1 on 2022-12-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0044_localizedtext_concept_nam_name_05c19d_hash_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalizedText',
            new_name='ConceptName',
        ),
    ]
