# Generated by Django 4.1.3 on 2023-01-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0045_rename_localizedtext_conceptname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='descriptions_old',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='names_old',
        ),
    ]
