# Generated by Django 4.1.3 on 2023-01-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0046_remove_concept_descriptions_old_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM concept_names where concept_id is null;
            """
        )
    ]
