# Generated by Django 4.1.3 on 2023-01-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0049_remove_concept_concepts_public_conditional_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_public_cond',
        ),
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_ver_public_cond2',
        ),
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_ver_all_for_count2',
        ),
    ]
