# Generated by Django 4.1.7 on 2023-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0052_remove_concept_concepts_all_for_count3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_class',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='datatype',
            field=models.TextField(db_index=True),
        ),
    ]
