# Generated by Django 4.1.7 on 2023-03-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0053_alter_concept_concept_class_alter_concept_datatype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('retired', True), ('id', models.F('versioned_object_id'))), fields=['parent_id'], name='concepts_retired_count_idx'),
        ),
    ]
