# Generated by Django 4.1.7 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0056_remove_concept_concepts_updated_6490d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concept',
            name='concepts_uri_trgm_id_gin_idx',
        ),
        migrations.AlterField(
            model_name='concept',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
