# Generated by Django 4.1.7 on 2023-04-13 11:25

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0058_remove_concept_concepts_is_late_2ce198_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='mnemonic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-zA-Z0-9\\-\\.\\_\\@\\+\\%\\s]+$'))]),
        ),
    ]
