# Generated by Django 4.1.7 on 2023-04-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0059_alter_concept_mnemonic'),
    ]

    operations = [
        migrations.RunSQL(
            'drop index if exists concepts_public_access_idx;'
        )
    ]
