# Generated by Django 4.1.7 on 2023-04-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0061_remove_concept_concepts_public__932f92_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conceptdescription',
            name='concept_des_locale_e8d16e_idx',
        ),
        migrations.RemoveIndex(
            model_name='conceptdescription',
            name='concept_des_locale__4f2050_idx',
        ),
        migrations.RemoveIndex(
            model_name='conceptname',
            name='concept_nam_locale__931ea0_idx',
        ),
    ]
