# Generated by Django 4.1.7 on 2023-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0062_remove_conceptdescription_concept_des_locale_e8d16e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_class',
            field=models.TextField(),
        ),
    ]
