# Generated by Django 4.1.7 on 2023-04-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0064_alter_concept_datatype'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conceptdescription',
            name='concept_des_name_c78c88_hash',
        ),
        migrations.RemoveIndex(
            model_name='conceptdescription',
            name='concept_des_type_8be5a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='conceptdescription',
            name='concept_des_created_68d73f_idx',
        ),
    ]
