# Generated by Django 4.1.7 on 2023-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0065_remove_conceptdescription_concept_des_name_c78c88_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='conceptdescription',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='conceptname',
            name='checksums',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
