# Generated by Django 4.1.7 on 2023-04-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0067_remove_concept_default_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='name',
        ),
    ]
