# Generated by Django 4.2.2 on 2023-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0068_remove_concept_full_name_remove_concept_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('id', models.F('versioned_object_id')), ('retired', False)), fields=['parent_id', 'id', 'retired'], name='concepts_parent_active'),
        ),
    ]
