# Generated by Django 4.2.4 on 2023-09-12 02:46

from django.db import migrations
from django.db.models import F, OuterRef
from django.db.models.functions import Coalesce


def update_updated_by(apps, schema_editor):
    Concept = apps.get_model('concepts', 'Concept')
    # Find the latest versions for each versioned_object_id
    latest_versions = Concept.objects.filter(
        versioned_object_id=OuterRef('versioned_object_id')
    ).filter(is_latest_version=True).order_by('-created_at')

    # Use Subquery to get the latest_version for each concept
    subquery = latest_versions.values('updated_by')[:1]

    # Update only the concepts where a latest version exists
    Concept.objects.filter(
        id=F('versioned_object_id'),
        versioned_object_id__in=latest_versions.values('versioned_object_id')
    ).update(updated_by=Coalesce(subquery, F('updated_by')))


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0069_concept_concepts_parent_active'),
    ]

    operations = [
        migrations.RunPython(update_updated_by)
    ]
