# Generated by Django 4.2.4 on 2023-10-03 09:42

from django.db import migrations
from django.db.models import F


def remove_duplicate_lookup_concepts(apps, schema_editor):
    Concept = apps.get_model('concepts', 'Concept')
    for parent_id in range(1, 7):  # ['Locales', 'Classes', 'Datatypes', 'DescriptionTypes', 'NameTypes', 'MapTypes']
        for mnemonic in set(Concept.objects.filter(
                parent_id=parent_id, id=F('versioned_object_id')).values_list('mnemonic', flat=True)):
            keep_concept = Concept.objects.filter(parent_id=parent_id, mnemonic=mnemonic).order_by('-id').first()
            Concept.objects.filter(
                parent_id=parent_id, mnemonic=mnemonic
            ).exclude(versioned_object_id=keep_concept.versioned_object_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0070_auto_20230912_0246'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_lookup_concepts)
    ]
