# Generated by Django 4.2.4 on 2023-12-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0071_auto_20231003_0942'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('is_latest_version', True), models.Q(('id', models.F('versioned_object_id')), _negated=True)), fields=['versioned_object_id', '-created_at'], name='concepts_latest'),
        ),
    ]
