# Generated by Django 4.2.4 on 2023-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0072_concept_concepts_latest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(condition=models.Q(('locale_preferred', True)), fields=['concept', 'locale_preferred', 'locale', '-created_at'], name='preferred_locale'),
        ),
    ]
