# Generated by Django 4.2.4 on 2024-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0073_conceptname_preferred_locale'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['id'], name='repo_version_concepts'),
        ),
    ]
