# Generated by Django 4.2.4 on 2024-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0074_concept_repo_version_concepts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concept',
            name='repo_version_concepts',
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('retired', False)), fields=['id', '-updated_at'], name='repo_version_concepts'),
        ),
    ]
