# Generated by Django 4.2.16 on 2025-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0075_remove_concept_repo_version_concepts_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            'create index if not exists concepts_repo_list_idx on concepts(parent_id, updated_at desc) '
            'where not retired and is_active and id = versioned_object_id;'
        )
    ]
