# Generated by Django 4.2.16 on 2025-02-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0076_auto_20250224_1005'),
    ]

    operations = [
        migrations.RunSQL(
            'create index if not exists concepts_updated_active_idx on concepts(updated_at desc) where not retired and is_active;')
        # for repo version concepts
    ]
