# Generated by Django 4.2.16 on 2025-09-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0077_auto_20250226_0548'),
    ]

    operations = [
        migrations.RunSQL('create index if not exists concepts_retired on concepts (id) where retired;'),
        migrations.RunSQL('create index if not exists concepts_parent_versioned_retired on concepts (parent_id) where id = versioned_object_id and retired;')
    ]
