# Generated by Django 5.1.15 on 2026-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0079_concepts_sources_source_concept_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptdescription',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptname',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
