# Generated by Django 5.1.15 on 2026-05-04 15:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0080_conceptdescription_retired_conceptname_retired'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conceptname',
            name='preferred_locale',
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='concept_des_name_c78c88_hash'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['locale'], name='concept_des_locale_e8d16e_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['created_at'], name='concept_des_created_68d73f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['type'], name='concept_des_type_8be5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptdescription',
            index=models.Index(fields=['retired'], name='concept_des_retired_77ec26_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(fields=['retired'], name='concept_nam_retired_e239e1_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(condition=models.Q(('retired', False)), fields=['locale'], name='active_locale'),
        ),
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(condition=models.Q(('retired', False)), fields=['-created_at'], name='last_created_locale'),
        ),
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(condition=models.Q(('locale_preferred', True), ('retired', False)), fields=['-created_at'], name='last_preferred_locale'),
        ),
        migrations.AddIndex(
            model_name='conceptname',
            index=models.Index(condition=models.Q(('locale_preferred', True), ('retired', False)), fields=['concept', 'locale_preferred', 'locale', '-created_at'], name='preferred_locale'),
        ),
    ]
