# Generated by Django 5.1.15 on 2026-05-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0081_remove_conceptname_preferred_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='retire_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptdescription',
            name='retire_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptname',
            name='retire_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
