# Generated by Django 5.1.15 on 2026-06-18 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0083_concept_concepts_prev_version'),
        ('sources', '0045_auto_20250821_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(condition=models.Q(('is_active', True), ('is_latest_version', False)), fields=['versioned_object_id', '-created_at'], name='concepts_prev_ver_non_latest'),
        ),
    ]
