# Generated by Codex on 2026-09-21

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
from django.db.models.functions import Upper


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('concepts', '0085_concept_head_parent_updated'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='conceptname',
            index=models.Index(
                Upper('name'), 'locale',
                name='concept_nam_upper_locale_idx',
                condition=models.Q(retired=False),
            ),
        ),
    ]
