# Generated by Codex on 2026-09-21

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models
from django.db.models.functions import MD5, Upper


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('concepts', '0086_conceptname_upper_name_locale_active'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='conceptname',
            name='concept_nam_upper_locale_idx',
        ),
        AddIndexConcurrently(
            model_name='conceptname',
            index=models.Index(
                MD5(Upper('name')), 'locale',
                name='concept_nam_md5_upper_loc_idx',
                condition=models.Q(retired=False),
            ),
        ),
    ]
