# Generated by Django 5.2.17 on 2026-09-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0087_conceptname_md5_upper_name_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='public_access',
            field=models.CharField(blank=True, choices=[('View', 'View'), ('None', 'None')], default='View', max_length=16),
        ),
    ]
