# Generated by Django 5.2.17 on 2026-10-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0088_conceptname_md5_upper_unaccent_name_locale'),
        ('concepts', '0088_retire_public_edit_access'),
    ]

    operations = [
    ]
