from django.urls import path

from core.concepts.feeds import ConceptFeed
from . import views
from .constants import CONCEPT_PATTERN as NAMESPACE_PATTERN

urlpatterns = [
    path('', views.ConceptListView.as_view(), name='concept-list'),
    path(
        "<str:concept>/",
        views.ConceptRetrieveUpdateDestroyView.as_view(),
        name='concept-detail'
    ),
    path(
        "<str:concept>/reactivate/",
        views.ConceptReactivateView.as_view(),
        name='concept-reactivate'
    ),
    path(
        "<str:concept>/children/",
        views.ConceptChildrenView.as_view(),
        name='concept-children'
    ),
    path('<str:concept>/atom/', ConceptFeed()),
    path(
        "<str:concept>/descriptions/",
        views.ConceptDescriptionListCreateView.as_view(),
        name='concept-descriptions'
    ),
    path(
        '<str:concept>/descriptions/<str:uuid>/',
        views.ConceptDescriptionRetrieveUpdateDestroyView.as_view(),
        name='concept-description'
    ),
    path(
        "<str:concept>/names/",
        views.ConceptNameListCreateView.as_view(),
        name='concept-names'
    ),
    path(
        '<str:concept>/names/<str:uuid>/',
        views.ConceptNameRetrieveUpdateDestroyView.as_view(),
        name='concept-name'
    ),
    path(
        '<str:concept>/extras/',
        views.ConceptExtrasView.as_view(),
        name='concept-extras'
    ),
    path(
        '<str:concept>/extras/<str:extra>/',
        views.ConceptExtraRetrieveUpdateDestroyView.as_view(),
        name='concept-extra'
    ),
    path(
        "<str:concept>/versions/",
        views.ConceptVersionsView.as_view(),
        name='concept-version-list'
    ),
    path(
        "<str:concept>/mappings/",
        views.ConceptMappingsView.as_view(),
        name='concept-mapping-list'
    ),
    path(
        '<str:concept>/<str:concept_version>/',
        views.ConceptVersionRetrieveView.as_view(),
        name='concept-version-detail'
    ),
    path(
        '<str:concept>/<str:concept_version>/mappings/',
        views.ConceptMappingsView.as_view(),
        name='concept-version-mapping-list'
    ),
    path(
        '<str:concept>/<str:concept_version>/descriptions/',
        views.ConceptDescriptionListCreateView.as_view(),
        name='concept-descriptions'
    ),
    path(
        '<str:concept>/<str:concept_version>/descriptions/<str:uuid>/'.format(
            pattern=NAMESPACE_PATTERN
        ),
        views.ConceptDescriptionRetrieveUpdateDestroyView.as_view(),
        name='concept-name'
    ),
    path(
        '<str:concept>/<str:concept_version>/extras/',
        views.ConceptExtrasView.as_view(),
        name='concept-extras'
    ),
    path(
        '<str:concept>/<str:concept_version>/extras/<str:extra>/'.format(
            pattern=NAMESPACE_PATTERN
        ),
        views.ConceptExtraRetrieveUpdateDestroyView.as_view(),
        name='concept-extra'
    ),
    path(
        '<str:concept>/<str:concept_version>/names/',
        views.ConceptNameListCreateView.as_view(),
        name='concept-names'
    ),
    path(
        '<str:concept>/<str:concept_version>/names/<str:uuid>/'.format(
            pattern=NAMESPACE_PATTERN
        ),
        views.ConceptNameRetrieveUpdateDestroyView.as_view(),
        name='concept-name'
    ),
]
