# Generated by Django 5.1.15 on 2026-09-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_versionchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionchangelog',
            name='extras',
            field=models.JSONField(default=dict),
        ),
    ]
