# Generated by Django 3.0.9 on 2021-02-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_configs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientconfig',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='clientconfig',
            name='page_size',
        ),
    ]
