# Generated by Django 3.0.9 on 2021-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_configs', '0002_auto_20210204_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfig',
            name='name',
            field=models.TextField(default='View Configuration'),
        ),
    ]
