# Generated by Django 3.0.9 on 2021-02-11 07:06

from django.db import migrations
from pydash import get


def update_tab_fields_config_structure(apps, schema_editor):
    ClientConfig = apps.get_model('client_configs', 'ClientConfig')
    for config in ClientConfig.objects.all():
        for tab in config.config.get('tabs', []):
            fields = get(tab, 'fields')
            if isinstance(fields, dict):
                tab['fields'] = [{k: v} for k, v in fields.items()]
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('client_configs', '0003_auto_20210205_1010'),
    ]

    operations = [
        migrations.RunPython(update_tab_fields_config_structure)
    ]
