# Generated by Django 3.1.6 on 2021-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_configs', '0004_auto_20210211_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfig',
            name='config',
            field=models.JSONField(),
        ),
    ]
