# Generated by Django 3.1.8 on 2021-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_configs', '0005_auto_20210326_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
